version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # 전체 프로젝트 마운트하지만 문제되는 폴더들은 익명 볼륨으로 오버라이드
      - .:/app
      # 컨테이너 내부의 node_modules와 .next 폴더 보호 (호스트 것으로 덮어쓰지 않음)
      - /app/node_modules
      - /app/.next
      # NAS 공유 폴더를 컨테이너 내부에 마운트
      - /volume1/data:/app/data
    env_file:
      - .env.local # 환경변수 파일
    environment:
      - DATA_DIR=/app/data # 데이터 디렉토리 환경변수 설정
    restart: always # 컨테이너가 죽었을 때 자동 재시작
